name: Java Web App CI/CD

on:
  push:
    branches:
      - main  # You can specify your main branch here

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
    - uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '17'
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload artifacts to AWS S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 # Replace with your desired AWS region


    - name: Build with Maven
      run: | 
        #mvn clean package  # Adjust your build command as needed
        ls
        pwd
        mvn --version
        mvn clean
        mvn install
        cd target
        ls
        aws s3 cp Menu-Driven-0.0.1-SNAPSHOT.jar s3://online-book-store-iiit/

    - name: Create Docker Build and Upload to ECR 
      run: | 
        cd CrudDemoWithMySql
        aws s3 cp s3://online-book-store-iiit/Menu-Driven-0.0.1-SNAPSHOT.jar ./
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s3c4l2m0
        docker build -t online-book .
        docker tag online-book:latest public.ecr.aws/s3c4l2m0/online-book:latest
        docker push public.ecr.aws/s3c4l2m0/online-book:latest
